//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavingStepByStep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonne
    {
        public string Telephone { get; set; }
        public string CarteID { get; set; }
        public string TypeCarte { get; set; }
        public string Designation { get; set; }
        public string Prenom { get; set; }
        public string NumMaison { get; set; }
        public string Avenue { get; set; }
        public string Quartier { get; set; }
        public string Commune { get; set; }
        public string Ville { get; set; }
        public string Nationalite { get; set; }
        public Nullable<System.DateTime> Datenaissance { get; set; }
        public string LieuNaissance { get; set; }
    }
}
